name: Build Test and Push image on merge to main

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - code-workflow

jobs:
  build-test-and-push-main:
    runs-on: ubuntu-latest
    environment: aks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install Python dependencies
        run: |
          pip install -r src/requirements.txt

#      - name: Run tests (if any)
#        run: |
#          pytest src/  # Adjust if your tests are also in the src directory

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          auth-type: service_principal

      - name: Login to Azure Container Registry
        run: |
          az acr login -n ${{ vars.AZURE_REGISTRY_URL }}

      - name: Set Git Hash env Variable
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.AZURE_REGISTRY_URL }}/hello/hello-py:${{ env.SHORT_SHA }} .

      - name: Test Docker image
        run: |
          docker run --rm -d --name hello-py-test -p 5000:5000 ${{ vars.AZURE_REGISTRY_URL }}/hello/hello-py:${{ env.SHORT_SHA }}
          sleep 10  # Wait a few seconds for the container to start
          docker logs hello-py-test
          curl -f http://localhost:5000/ || exit 1  # Check if the app is running
          docker stop hello-py-test

      - name: Push Docker image to ACR - SHORT SHA
        run: |
          docker push ${{ vars.AZURE_REGISTRY_URL }}/hello/hello-py:${{ env.SHORT_SHA }}  

      - name: Tag and Push Docker image to ACR - LATEST
        run: |
          docker tag ${{ vars.AZURE_REGISTRY_URL }}/hello/hello-py:${{ env.SHORT_SHA }} ${{ vars.AZURE_REGISTRY_URL }}/hello/hello-py:latest
          docker push ${{ vars.AZURE_REGISTRY_URL }}/hello/hello-py:latest
