name: Deploy to AKS

on:
  workflow_dispatch:
  workflow_call:
#  workflow_run:
#    workflows: [ "Build Test and Push image on merge to main" ]  # The name of the primary workflow
#    types:
#      - completed


jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    environment: aks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          auth-type: service_principal

      - name: Login to ACR
        run: |
          az acr login --name acrjavahelena
          az acr repository list --name acrjavahelena --output table

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: javahelenaResourceGroup
          cluster-name: javahelena-aks

      - name: Lint Helm Chart
        run: |
          cd k8s/hello-py
          helm lint

      - name: Deploy Helm Chart
        run: |
          cd k8s/hello-py
          helm upgrade --install --namespace hello hello-py . -f values.yaml