name: Update Helm Revision in Git

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-helm-revision:
    runs-on: ubuntu-latest
    environment: aks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git Hash env Variable
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Print current working directory
        run: |
          echo "Current working directory:"
          pwd

      - name: Navigate to the root of the git repository
        id: root-dir
        run: |
          ROOT_DIR=$(git rev-parse --show-toplevel)
          echo "ROOT_DIR=$ROOT_DIR" >> $GITHUB_ENV

      - name: List contents of the directory
        run: |
          cd ${{ env.ROOT_DIR }}
          echo "Listing contents of k8s/hello-py/templates:"
          ls -l k8s/hello-py/templates

      - name: Verify file existence
        run: |
          if [ ! -f k8s/hello-py/templates/deployments.yaml ]; then
            echo "File not found: k8s/hello-py/templates/deployments.yaml"
            exit 1
          fi

      - name: Update the Helm revision in the helm values file
        run: |
          echo "Updating the Helm revision in the helm values file..."
          sed -i "s/helm.sh\/revision: \".*\"/helm.sh\/revision: \"${{ env.SHORT_SHA }}\"/g" k8s/hello-py/templates/deployments.yaml
          cat k8s/hello-py/templates/deployments.yaml

      - name: Commit the changes to the Helm revision
        run: |
          echo "Committing the changes to the Helm revision..."
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add k8s/hello-py/templates/deployments.yaml
          git commit -m "Update Helm revision to ${{ env.SHORT_SHA }}"
          git push