name: Update Helm Revision in Git

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-helm-revision:
    runs-on: ubuntu-latest
    environment: aks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git Hash env Variable
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Print current working directory
        run: |
          echo "Current working directory:"
          pwd

      - name: Navigate to the root of the git repository
        id: root-dir
        run: |
          ROOT_DIR=$(git rev-parse --show-toplevel)
          echo "ROOT_DIR=$ROOT_DIR" >> $GITHUB_ENV
          pwd

      - name: List contents of the directory
        run: |
          cd ${{ env.ROOT_DIR }}
          pwd
          echo "Listing contents of k8s/hello-py/templates:"
          ls -l k8s/hello-py/templates

#      - name: Verify file existence
#        run: |
#          cd k8s/hello-py/templates
#          pwd
#          if [ ! -f deployments.yaml ]; then
#            echo "File not found: k8s/hello-py/templates/deployments.yaml"
#            exit 1
#          fi

      - name: Update the Helm revision in the helm values file
        run: |
          pwd
          cd k8s/hello-py/templates
          pwd
          echo "Updating the Helm revision in the helm values file..."
          sed -i "s/helm.sh\/revision: \".*\"/helm.sh\/revision: \"${{ env.SHORT_SHA }}\"/g" deployment.yaml
          cat deployment.yaml

      - name: Commit and Push Helm Update
        run: |
          pwd
          cd k8s/hello-py/templates
          pwd
          echo "Committing the changes to the Helm revision..."
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}