name: Update Helm Revision in Git

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build Test and Push image on merge to main" ]  # The name of the primary workflow
    types:
      - completed

jobs:
  update-helm-revision:
    runs-on: ubuntu-latest
    environment: aks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git Hash env Variable
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update the Helm revision in the helm values file
        run: |
          echo "Updating the Helm revision in the helm values file..."
          sed -i "s/helm.sh\/revision: \".*\"/helm.sh\/revision: \"${{ env.SHORT_SHA }}\"/g" k8s/hello-java/templates/deployment.yaml
          cat k8s/hello-java/templates/deployment.yaml

      - name: Commit the changes to the Helm revision
        run: |
          echo "Committing the changes to the Helm revision..."
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add k8s/hello-java/templates/deployment.yaml
          git commit -m "Update Helm revision to ${{ env.SHORT_SHA }}"
          git push
   



